- platform: broadlink
  host: !secret broadlink_host
  mac: !secret broadlink_mac
  friendly_name: 'Dining Room Mini'
  type: rm_mini
  timeout: 15
  switches:
    ac:
      friendly_name: Air Conditioner
      command_off: 'JgC8AXM4DyoQDQ8NEA0PKg8NEA0PDRAMECoPDQ8qECoPDRAqDyoPKhApECoPDQ8NDyoQDQ8ODg0QDQ8ODwwQKg8qDyoQKg8NEA0PDg4NEA0PDg8MEA0PDg8NDg4PDg8NDg4PDg8NEAwPDg8NEA0NDw8NEA0PDQ8NECoPDRANDQ8PDRANDBAPAAPZcjkQKg8NEA0MEA8qDg8PDRAMDw4PKg8ODyoPKg8NDyoPKw4rDisOKw8ODw4PKg8ODQ4PDg8ODwwQDQ8ODw0MEA4PDg4PDQ4PDw0PDQ4PDg4PDgwQDg4PDg4ODyoOKw8ODw4PKg4PCxAPKw4ODysODg8NDg8PDQ4ODg8PDQ8OCxEODg8rDyoOKw8qEA0PKg8NDyoPDg8ODw0MEA8ODw0PDQ4PDg4PDgwQDg4PDgwQDg4PDg4ODg4PDg4PCxEPDQ8ODg0QDQ8ODw0MEA4PDg4MEBANDg4PDQ4PDg8ODgwQDg8ODg8NDg8ODg8OCxEPDQ8ODBAODg8ODg4ODg8ODg8LLg0sDg4PDg8NDw0PDg8NDw4MEA4ODg8PDQ4ODw4ODg4ODw4PDgsuDQ8PKg8qDw4PKg8rDgANBQAAAAAAAAAAAAAAAA=='
      command_on: 'JgC8AXQ4DyoQDA8ODg4PKw8MEA0PDg4ODysODRAqDisPDg4rDyoQKg8qDyoPDg4NDysODg8ODg8ODQ8ODg8PKg8qDS0OKw4ODg4NEA4ODg4PDg4ODw0PDg4PDg0PDg4PDg4PDQ4PDg4PDQ4PDg4PDg4ODg4PDg8NDisODwwQDg4NEAwQDw4OAAPZcTsNLA0QDQ8NDw0sDg8NEAwQDQ8NLA4PDSwOLA0PDSwOLA0sDSwOLA0ODg8NLA0QDQ8NDw4PDQ8NDw4PDRANDg4PDRANDw0PDRANDw0PDBENDw4sDQ8NDw0QDSwNLA4PDQ8NLA0PDg8NLA4ODS0NDw0QDQ8NDw0QDQ8ODg0QDQ8ODw0sDS0MLQ0sDQ8NLA4PDSwNEA0PDQ8ODw0PDQ8ODw0QDA8ODw0QDQ4NEA0QDBANDwwRDBAODg0QDQ8NDw0QDQ8ODwwQDQ8ODw0PDQ8NEA0QDA8ODw0QDA8NEA0QDQ8NDw0QDQ8NDw0QDBAODg0QDQ8NEA0PDRAMEA0PDBENLA0sDRANDw0PDRANDw0PDRANDw4ODg8MEA0QDQ8MEQwQDQ8NLA4sDQ8NLA4sDQ8OLA0sDQANBQAAAAAAAAAAAAAAAA=='
    hutch:
      friendly_name: Hutch Lights
      command_on: 'JgBYAAABLJYTExEVERQTEhIUFBETExAWETkROhI5FDYRFRI5EDoTORI4EToSExIUFBETExEUEhMTExEVETkROhI5EjkQOhM4EwAFUwABLEwQAAx8AAEsSxEADQU=='
      command_off: 'JgBYAAABLJYUEhEVERMTExIUEhMSFBEUEjkQOhM5EjgRFRE5EjkSORITEjkSExMTERURFBITEhQSOBEVEjkQOhM4EjkRORM5EgAFUwABLEsRAAx6AAEsSxEADQU=='
    hutch_100:
      friendly_name: Hutch Lights 100
      command_on: 'JgBYAAABLJYSExIUEhMSFBAVEhMSFBEVEjgROhQ3EjgRFRI5EDoUNxITExMRORUREhQSExQREhQSORA6EhQRORU3EjgROhI5EgAFVAABLUoQAAx6AAEtSxEADQU=='
    hutch_50:
      friendly_name: Hutch Lights 50
      command_on: 'JgBQAAABLJUUEhEVEhITExEVEhMUEREVEjkQOhI5EjkRFRM3EToSORI4ERUSOBEVEhMUEhAVExISFBA6EhQRORQ4EjgROhQ3EgAFUwABK0wRAA0FAAAAAAAAAAA=='
    hutch_10:
      friendly_name: Hutch Lights 10
      command_on: 'JgBQAAABLpQUEhAVEhMVEREVEhMTExEUEjkRORM5EjgRFRI5EDoUNxI5ERUSOBEVEjgRFRITExMRFRI4ERUSOBEVEjkQOhQ4EgAFUwABLEsRAA0FAAAAAAAAAAA=='

