- platform: broadlink
  host: !secret broadlink_host
  mac: !secret broadlink_mac
  friendly_name: 'Dining Room Mini'
  type: rm_mini
  timeout: 15
#  switches:
#    ac:
#      friendly_name: Air Conditioner
#      command_on: ''
#      command_off: ''
