- platform: template
  switches:
    television:
      value_template: "{% if is_state('sensor.living_room', 'Watch TV') %}on{% else %}off{% endif %}"
      friendly_name: Television
      turn_on:
        service: remote.turn_on
        entity_id: remote.living_room
        data:
          activity: "25295743"
      turn_off:
        service: remote.turn_off
        entity_id: remote.living_room
    roku:
      value_template: "{% if is_state('sensor.living_room', 'Watch Roku') %}on{% else %}off{% endif %}"
      friendly_name: Roku
      turn_on:
        service: remote.turn_on
        entity_id: remote.living_room
        data:
          activity: "21814656"
      turn_off:
        service: remote.turn_off
        entity_id: remote.living_room
    playstation:
      value_template: "{% if is_state('sensor.living_room', 'Play PS4') %}on{% else %}off{% endif %}"
      friendly_name: Playstation
      turn_on:
        service: remote.turn_on
        entity_id: remote.living_room
        data:
          activity: "23177182"
      turn_off:
        service: remote.turn_off
        entity_id: remote.living_room
    music:
      value_template: "{% if is_state('sensor.living_room', 'Listen to Music') %}on{% else %}off{% endif %}"
      friendly_name: Stereo
      turn_on:
        service: remote.turn_on
        entity_id: remote.living_room
        data:
          activity: "22062061"
      turn_off:
        service: remote.turn_off
        entity_id: remote.living_room
