homeassistant:
  name: Home
  latitude: !secret homelatitude
  longitude: !secret homelongitude
  elevation: !secret elevation
  unit_system: imperial
  time_zone: America/New_York
  customize: !include_dir_merge_named customizations

zone: !include_dir_merge_list zones

zeroconf:

config:

frontend:
  themes:

# thanks to jmart518 (profile: https://community.home-assistant.io/u/jmart518 reference: https://community.home-assistant.io/t/share-your-themes/22018/2)

    red:
      primary-color: "#f44336"
    pink:
      primary-color: "#e91e63"
    purple:
      primary-color: "#9c27b0"
    deep-purple:
      primary-color: "#673ab7"
    indigo:
      primary-color: "#3f51b5"
    blue:
      primary-color: "#2196f3"
    light-blue:
      primary-color: "#03a9f4"
    cyan:
      primary-color: "#00bcd4"
    teal:
      primary-color: "#009688"
    green:
      primary-color: "#4caf50"
    light-green:
      primary-color: "#8bc34a"
    lime:
      primary-color: "#cddc39"
    yellow:
      primary-color: "#ffeb3b"
    amber:
      primary-color: "#ffc107"
    orange:
      primary-color: "#ff9800"
    deep-orange:
      primary-color: "#ff5722"
    brown:
      primary-color: "#795548"
    grey:
      primary-color: "#9e9e9e"
    blue-grey:
      primary-color: "#607d8b"

# thanks to arsaboo (profile: https://community.home-assistant.io/u/arsaboo reference: https://github.com/arsaboo/homeassistant-config/blob/master/configuration.yaml#L65_)

    minimal:
      dark-primary-color: "#192231"
      primary-color: "#98878f"
      light-primary-color: "#98878f"
      paper-toggle-button-checked-ink-color: "#494e6b"
      paper-toggle-button-checked-button-color: "#494e6b"
      paper-toggle-button-checked-bar-color: "#494e6b"
      paper-slider-knob-color: "#494e6b"
      paper-slider-knob-start-color: "#494e6b"
      paper-slider-pin-color: "#494e6b"
      paper-slider-active-color: "#494e6b"
    stormy_hues:
      dark-primary-color: "#192231"
      primary-color: "#98878f"
      light-primary-color: "#98878f"
      paper-toggle-button-checked-ink-color: "#494e6b"
      paper-toggle-button-checked-button-color: "#494e6b"
      paper-toggle-button-checked-bar-color: "#494e6b"
      paper-slider-knob-color: "#494e6b"
      paper-slider-knob-start-color: "#494e6b"
      paper-slider-pin-color: "#494e6b"
      paper-slider-active-color: "#494e6b"
    vintage:
      dark-primary-color: "#373f27"
      primary-color: "#636b46"
      light-primary-color: "#e9e7da"
      paper-toggle-button-checked-ink-color: "#cda34f"
      paper-toggle-button-checked-button-color: "#cda34f"
      paper-toggle-button-checked-bar-color: "#cda34f"
      paper-slider-knob-color: "#cda34f"
      paper-slider-knob-start-color: "#cda34f"
      paper-slider-pin-color: "#cda34f"
      paper-slider-active-color: "#cda34f"
    done1:
      dark-primary-color: "#565656"
      primary-color: "#C09F80"
      light-primary-color: "#D7CEC7"
      paper-toggle-button-checked-ink-color: "#76323F"
      paper-toggle-button-checked-button-color: "#76323F"
      paper-toggle-button-checked-bar-color: "#76323F"
      paper-slider-knob-color: "#76323F"
      paper-slider-knob-start-color: "#76323F"
      paper-slider-pin-color: "#76323F"
      paper-slider-active-color: "#76323F"
      paper-slider-secondary-color: "#FFE0B2"

# thanks to ahs (profile: https://community.home-assistant.io/u/ahs reference: https://community.home-assistant.io/t/share-your-themes/22018/6)

    ahs:
      primary-color: '#333577'
      primary-text-color: '#090A3B'
      paper-grey-50: '#DEDEDE'
      primary-background-color: '#FFFFFF'
      text-primary-color: '#FFFFFF'
      paper-toggle-button-checked-button-color: '#FFD700'
      paper-toggle-button-checked-bar-color: '#FFA726'
      paper-toggle-button-checked-ink-color: '#FFA726'
      paper-toggle-button-unchecked-button-color: '#EAEAEA'
      paper-toggle-button-unchecked-bar-color: '#DEDEDE'
      paper-toggle-button-unchecked-ink-color: '#DEDEDE'
      paper-slider-knob-color: '#FFD700'
      paper-slider-knob-start-color: '#FFD700'
      paper-slider-pin-color: '#FFD700'
      paper-slider-active-color: '#FFD393'
      paper-slider-secondary-color: '#DEDEDE'
      paper-slider-container-color: '#F2F2F2'
      ha-label-badge-color: '#DEDEDE'
      paper-tabs-selection-bar-color: '#DEDEDE'


http:
  api_password: !secret http_password
  #use_x_forwarded_for: true
  #ip_ban_enabled: true
  #login_attempts_threshold: 3
  #trusted_networks: !secret home_networks

updater:
  reporting: no

discovery:

conversation:

history:

logbook:

sun:

automation: !include_dir_list automations/

scene: !include_dir_merge_list scenes/

sensor: !include_dir_merge_list sensors/

device_tracker: !include device_trackers.yaml

switch: !include_dir_merge_list switches/

notify: !include_dir_merge_list notifications/

group: !include_dir_merge_named groups/

camera: !include_dir_merge_list cameras/

binary_sensor: !include_dir_merge_list binary_sensors/

wake_on_lan:

recorder:
#  db_url: !secret mariadb_url

lametric:
  client_id: !secret lametric_client_id
  client_secret: !secret lametric_client_secret

# MQTT
mqtt:
  broker: !secret mqttbroker
  port: !secret mqttport
  username: !secret mqttusername
  password: !secret mqttpassword
  birth_message:
    topic: 'hass/status'
    payload: 'online'
    qos: 1
    retain: true
  will_message:
    topic: 'hass/status'
    payload: 'offline'
    qos: 1
    retain: true

hue:
  bridges:
    - host: !secret hue_host_ip
      allow_unreachable: true
      allow_hue_groups: false

# emulated hue bridge
emulated_hue:
  type: alexa
  advertise_ip: !secret emulated_hue_advertise_ip
  advertise_port: !secret emulated_hue_advertise_port
  listen_port: !secret emulated_hue_listen_port
  upnp_bind_multicast: true
  off_maps_to_on_domains:
    - scene
  expose_by_default: true
  exposed_domains:
    - switch
    - scene

# media players
media_player:
  - platform: onkyo
    host: !secret onkyo_receiver_host
    name: Living Room Receiver
    zone2: false
    zone3: false
    sources:
      video2: 'Nvidia Shield'
      bd: 'Playstation'
      game: 'Nintendo Switch'
      net: 'Network Stream'
      #video3: 'Nintendo Switch'
      fm: 'FM Radio'
      am: 'AM Radio'
      bluetooth: 'Bluetooth'
  - platform: plex

remote:
  - platform: harmony
    name: Living Room
    host: !secret harmony_hub_living_room
  - platform: harmony
    name: Bedroom
    host: !secret harmony_hub_bedroom

digital_ocean:
  access_token: !secret digital_ocean_api_token

weblink:
  entities:
    - name: Node Red Configuration
      url: !secret node_red_url
    - name: Router Configuration
      url: !secret router_url
      icon: mdi:router-wireless
    - name: Plex Web
      url: !secret plex_url
      icon: mdi:plex
    - name: FY Camera Configuration
      url: !secret mjpeg_camera_1_config_url
      icon: mdi:video
    - name: LR Camera Configuration
      url: !secret mjpeg_camera_2_config_url
      icon: mdi:video
    - name: Subsonic Web
      url: !secret subsonic_url
      icon: mdi:music-note
    - name: Sabnzbd
      url: !secret sabnzbd_url
      icon: mdi:download
    - name: Sonarr
      url: !secret sonarr_url
      icon: mdi:television-guide

netatmo:
  api_key: !secret netatmo_api_key
  secret_key: !secret netatmo_secret_key
  username: !secret netatmo_username
  password: !secret netatmo_password

tuya:
  username: !secret tuya_username
  password: !secret tuya_password
  country_code: 1
  platform: smart_life
