homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret homelatitude
  longitude: !secret homelongitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  customize:
    switch.patio_lamp:
      icon: mdi:lamp
    switch.salt_lamp:
      icon: mdi:lamp
    switch.roku:
      icon: mdi:television-guide
    switch.television:
      icon: mdi:television
    switch.music:
      icon: mdi:music-note
    switch.stereo:
      icon: mdi:music-note
    switch.playstation:
      icon: mdi:gamepad-variant
    scene.sunset_scene:
      icon: mdi:weather-sunset
    scene.work_scene:
      icon: mdi:worker
    scene.bedtime_scene:
      icon: mdi:hotel
    scene.power_down_scene:
      icon: mdi:power
    binary_sensor.tungsten:
      icon: mdi:laptop
    binary_sensor.meet:
      icon: mdi:laptop
    scene.sunrise_scene:
      icon: mdi:weather-sunset-up
    sensor.printer_status:
      icon: mdi:printer
    sensor.page_counter:
      icon: mdi:book-open-page-variant
    sensor.cartridge:
      icon: mdi:printer-alert
    switch.stereo_bluetooth_adapter:
      icon: mdi:music-note-bluetooth
    switch.security:
      icon: mdi:camera

zone: !include_dir_merge_list zones

# Show links to resources in log and frontend
#introduction:

# bonjour/avahi
zeroconf:

# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_password
  use_x_forwarded_for: true
  ip_ban_enabled: true
  login_attempts_threshold: 3
  #trusted_networks: !secret home_networks

# Checks for available updates
updater:
  reporting: no

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

automation: !include_dir_list automations/

scene: !include_dir_merge_list scenes/

# MQTT
mqtt:
  broker: !secret mqttbroker
  port: !secret mqttport
  username: !secret mqttusername
  password: !secret mqttpassword
  birth_message:
    topic: 'hass/status'
    payload: 'online'
    qos: 1
    retain: true
  will_message:
    topic: 'hass/status'
    payload: 'offline'
    qos: 1
    retain: true

sensor: !include_dir_merge_list sensors/

device_tracker: !include device_trackers.yaml

# phillips hue bridge
light:
  platform: hue
  host: !secret hue_host_ip
  allow_unreachable: true

# emulated hue bridge
emulated_hue:
  #no longer using this because removed --net=host from run
  #host_ip: !secret emulated_hue_host_ip
  type: alexa
  listen_port: !secret emulated_hue_listen_port
  off_maps_to_on_domains:
    - scene
  expose_by_default: true
  exposed_domains:
    - switch
    - scene

switch: !include_dir_merge_list switches

# media players
media_player:
  - platform: universal
    name: Living Room Media
    children:
      - media_player.roku_1gh31e025621
      - media_player.55h6sg
      - media_player.living_room_roku
  - platform: cast
    name: Office Chromecast
    host: !secret chromecastip

remote:
  - platform: harmony
    name: Living Room
    host: !secret harmonyhubip

# groups
group:
  bedroomlights:
    name: Bed Room Lights
    view: no
    entities:
      - light.bedroom_1
      - light.bedroom_2

  bedroom:
    view: yes
    entities:
      group.bedroomlights

  sparebedroomlights:
    name: Spare Bedroom Lights
    view: no
    entities:
      - light.spare_bedroom_1
      - light.spare_bedroom_2

  sparebedroom:
    name: Spare Bedroom
    view: yes
    entities:
      - group.sparebedroomlights

  livingroomoverhead:
    name: Living Room Overhead Lights
    view: no
    entities:
      - light.living_room__front_left
      - light.living_room__front_right
      - light.living_room__rear_left
      - light.living_room__rear_right

  alanfitbit:
    name: Alan's Fitbit Data
    view: no
    entities:
      - sensor.body_weight
      - sensor.body_fat
      - sensor.steps
      - sensor.resting_heart_rate
      - sensor.sleep_efficiency

  packages:
    name: Packages
    view: no
    entities:
      - sensor.usps
      - sensor.ups
      - sensor.fedex

  nas:
    name: NAS
    entities:
      - sensor.titanium_status
      - sensor.titanium_cpu_usage
      - sensor.titanium_memory_usage
      - sensor.titanium_volume_used_titanium

#  christmascactus:
#    name: Christmas Cactus
#    view: no
#    entities:
#      - sensor.christmas_cactus_conductivity
#      - sensor.christmas_cactus_light_intensity
#      - sensor.christmas_cactus_moisture
#      - sensor.christmas_cactus_temperature
#
#  lipstick:
#    name: Lipstick Plant
#    view: no
#    entities:
#      - sensor.lipstick_plant_conductivity
#      - sensor.lipstick_plant_light_intensity
#      - sensor.lipstick_plant_moisture
#      - sensor.lipstick_plant_temperature
#
#  elephantear:
#    name: Elephant Ear
#    view: no
#    entities:
#      - sensor.elephant_ear_conductivity
#      - sensor.elephant_ear_light_intensity
#      - sensor.elephant_ear_moisture
#      - sensor.elephant_ear_temperature

#  livingroomplants:
#    name: Living Room Plants
#    view: no
#    entities:
#      - group.christmascactus
#      - group.lipstick
#      - group.elephantear

  livingroom:
    name: Living Room
    view: yes
    entities:
      - group.livingroomoverhead
      - light.living_room_lamp
      - switch.salt_lamp
      - switch.stereo_bluetooth_adapter
#      - group.livingroomplants

  officelights:
    name: Office Lights
    view: no
    entities:
      - light.office_1
      - light.office_2

  office:
    name: Office
    view: yes
    entities:
      - group.officelights
      - group.system
      - group.server_stats
      - group.printer_stats
      - group.nas
      - group.packages

  basementlights:
    name: Basement Lights
    view: no
    entities:
      - light.basement_stairs
      - light.basement_middle
      - light.basement_front
      - light.basement_rear_left
      - light.basement_rear_right
      - light.laundry

  basement:
    name: Basement
    view: yes
    entities:
      - group.basementlights
      - light.laundry

  laundryroom:
    name: Laundry Room Lights
    view: no
    entities:
      - light.laundry
      - light.basement_stairs
      - light.basement_middle

  pantry:
    name: Pantry Lights
    view: no
    entities:
      - light.basement_stairs
      - light.basement_middle

  patio:
    name: Patio
    view: yes
    entities:
      - group.patiolights

  patiolights:
    name: Patio Lights
    view: no
    entities:
      - switch.patio_lamp

  people:
    name: People
    view: no
    entities:
      - device_tracker.alan_phone
      - device_tracker.robert_phone

  system:
    name: System Stats
    view: no
    entities:
      - sensor.cpu_use
      - sensor.ram_use

  server_stats:
    name: Server Status
    view: no
    entities:
      - sensor.sabnzbd_status
      - sensor.sabnzbd_speed
      - sensor.sabnzbd_queue
      - sensor.plex_info

  printer_stats:
    name: Printer Status
    entities:
      - sensor.printer_status
      - sensor.page_counter
      - sensor.cartridge

  weather:
    name: Weather
    view: no
    entities:
      - sensor.dark_sky_summary
      - sensor.dark_sky_temperature

digital_ocean:
  access_token: !secret digital_ocean_api_token

binary_sensor:
  - platform: digital_ocean
    droplets: !secret digital_ocean_droplets
  - platform: aurora
    forecast_threshold: 70

weblink:
  entities:
    - name: Router Configuration
      url: !secret router_url
      icon: mdi:router-wireless
    - name: CloudMQTT Console
      url: !secret cloudmqtt_url
      icon: mdi:message-settings-variant
    - name: Plex Web
      url: !secret plex_url
      icon: mdi:plex
    - name: FY Camera Configuration
      url: !secret mjpeg_camera_1_config_url
      icon: mdi:video
    - name: LR Camera Configuration
      url: !secret mjpeg_camera_2_config_url
      icon: mdi:video
    - name: Subsonic Web
      url: !secret subsonic_url
      icon: mdi:music-note
    - name: Sabnzbd
      url: !secret sabnzbd_url
      icon: mdi:download
    - name: Couch Potato
      url: !secret couch_potato_url
      icon: mdi:movie
    - name: Sonarr
      url: !secret sonarr_url
      icon: mdi:television-guide
    - name: Headphones
      url: !secret headphones_url
      icon: mdi:music-note

camera:
  - platform: mjpeg
    name: Front Yard Camera
    mjpeg_url: !secret mjpeg_camera_1_url
    username: !secret mjpeg_camera_1_username
    password: !secret mjpeg_camera_1_password
  - platform: mjpeg
    name: Living Room Camera
    mjpeg_url: !secret mjpeg_camera_2_url
    username: !secret mjpeg_camera_2_username
    password: !secret mjpeg_camera_2_password
  - platform: mjpeg
    name: Office Camera
    mjpeg_url: !secret mjpeg_camera_3_url
    username: !secret mjpeg_camera_3_username
    password: !secret mjpeg_camera_3_password

notify:
#  - platform: telegram
#    name: telegram_alan
#    api_key: !secret telegram_api_key
#    chat_id: !secret telegram_alan_chat_id
  - platform: nfandroidtv
    name: Living Room TV
    host: !secret nfandroidhost1
    color: grey
    transparency: 50%
    position: top-right
  - platform: nfandroidtv
    name: Bedroom TV
    host: !secret nfandroidhost2
    color: grey
    transparency: 50%
    position: top-right
