- platform: mikrotik
  host: !secret mikrotik_host
  port: !secret mikrotik_port
  username: !secret mikrotik_username
  password: !secret mikrotik_password
  interval_seconds: 30
  consider_home: 180
  track_new_devices: no
