- platform: netgear
  host: !secret netgear_host
  port: !secret netgear_port
  username: !secret netgear_username
  password: !secret netgear_password
  interval_seconds: 60
  consider_home: 180
  track_new_devices: no
