- platform: qnap
  host: !secret qnap_ip
  port: !secret qnap_port
  username: !secret qnap_username
  password: !secret qnap_password
  ssl: true
  verify_ssl: false
  monitored_conditions:
    - status
    - cpu_usage
    - memory_percent_used
    - volume_percentage_used
