- platform: netatmo
  station: home
  modules:
    outside:
      - temperature
      - humidity
      - rf_status
      - battery_vp
    indoor:
      - temperature
      - humidity
      - pressure
      - co2
      - noise
      - wifi_status
