- platform: pi_hole
  host: !secret pi_hole_host
  ssl: false
  monitored_conditions:
    - ads_blocked_today
    - ads_percentage_today
    - dns_queries_today
    - domains_being_blocked
    - queries_cached
    - queries_forwarded
    - unique_domains
