#- platform: usps
#  username: !secret usps_username
#  password: !secret usps_password
#  name: USPS
#  update_interval:
#    hours: 6
- platform: fedex
  username: !secret fedex_username
  password: !secret fedex_password
  name: FedEx
  scan_interval:
    hours: 6
- platform: ups
  username: !secret ups_username
  password: !secret ups_password
  name: UPS
  scan_interval:
    hours: 6
