- platform: snmp
  host: !secret printerip
  port: !secret printerport
  baseoid: 1.3.6.1.2.1.43.10.2.1.4.1.1
  name: Page Counter
- platform: snmp
  host: !secret printerip
  port: !secret printerport
  baseoid: 1.3.6.1.2.1.43.16.5.1.2.1.1
  name: Printer Status
- platform: snmp
  host: !secret printerip
  port: !secret printerport
  baseoid: 1.3.6.1.2.1.43.11.1.1.6.1.1
  name: Cartridge
