- platform: nut
  name: NUT UPS
  host: !secret nut_ups_host
  user: !secret nut_ups_user
  password: !secret nut_ups_password 
  resources:
    - ups.status
    - battery.charge
    - battery.voltage
    - battery.runtime
    - input.voltage
