alias: Sunrise Stuff
trigger:
  - platform: sun
    event: sunrise
    offset: "+00:30:00"
action:
  - service: scene.turn_on
    entity_id: scene.sunrise_scene
  - service: notify.slack_zerohalo
    data:
      message: "The sun is up!"
      title: "Sunrise"
  - service: notify.discord_zerohalo
    data:
      message: "The sun is up!"
      title: "Sunrise"
