alias: Sunset Lights On
trigger:
  - platform: sun
    event: sunset
    offset: "-00:15:00"
condition:
  - condition: state
    entity_id: group.living_room_overhead
    state: 'off'
action:
  - service: scene.turn_on
    entity_id: scene.sunset_scene
  - service: notify.living_room_tv
    data:
      message: "The sun is about to set. Turning on some lights."
      title: "Sunset"
  - service: notify.bedroom_tv
    data:
      message: "The sun is about to set. Turning on some lights."
      title: "Sunset"
  - service: notify.my_lametric
    data:
      message: "Sunset"
      title: "Sunset"
  - service: notify.slack_zerohalo
    data:
      message: "The sun is about to set. Turning on some lights."
      title: "Sunset"
  - service: notify.discord_zerohalo
    data:
      message: "The sun is about to set. Turning on some lights."
      title: "Sunset"
      target: !secret discord_target_notifications
  - service: notify.joao_apps
    data:
      message: "The sun is about to set. Turning on some lights."
      title: "Sunset"
